print("Welcome to the Band Name Generator!")
print("What is the name of the city you grew up in?")
city = input()
print("What is your nickname?")
nickname = input()
print("The name of your band could be " + city + " " + nickname + "!")
